baseurl = "http://linjinxing.github.io/"
languageCode = "zh-cn"
title = "彤星的博客"
# Enable comments by entering your Disqus shortname
# disqusShortname = "spf13"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
# Define the number of posts per site
paginate = 10
theme = "hugo-icarus"


[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you're
    author = "John Doe"
    bio = "Blogger - Programmer - Gopher"
    location = "Earth"
    site_description = ""
    copyright  = "Powered by [Hugo](//gohugo.io). Theme by [PPOffice](http://github.com/ppoffice)."

    # Format dates with Go's time formating
    date_format = "2006-01-02"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "首页"
    link   = "/"

[[params.menu]]
    before = true
    label  = "iOS"
    link   = "categories/ios"

[[params.menu]]
    before = true
    label  = "架构"
    link   = "categories/软件架构"

[[params.menu]]
    before = false
    label  = "程序人生"
    link   = "categories/程序人生"

[[params.menu]]
    before = false
    label  = "管理"
    link   = "categories/管理"

[[params.menu]]
    before = false
    label  = "敏捷开发"
    link   = "categories/敏捷开发"


[[params.menu]]
    before = false
    label  = "android"
    link   = "categories/android"

[[params.menu]]
    before = false
    label  = "产品"
    link   = "categories/产品"

[[params.menu]]
    before = false
    label  = "其它"
    link   = "categories/其它"

[[params.menu]]
    before = false
    label  = "个人简介"
    link   = "resume"



# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/digitalcraftsman"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# create automatically.
    github          = "digitalcraftsman"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = false
    tags = true
    tag_cloud = false


# git subtree push --prefix=public git@gitcafe.com:linjinxing/linjinxing.git gitcafe-pages
# git subtree add --prefix=public git@gitcafe.com:linjinxing/linjinxing.git gitcafe-pages --squash
# git subtree pull --prefix=public git@gitcafe.com:linjinxing/linjinxing.git gitcafe-pages
